[package]
name = "bessie_bin"
version = "0.0.3"
description = "a demo/test CLI for the Bessie cipher, NOT FOR PRODUCTION USE"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]
license = "CC0-1.0 OR Apache-2.0"
readme = "../../README.md"
repository = "https://github.com/oconnor663/bessie"

edition = "2021"

[[bin]]
name = "bessie"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.56"
bessie = { version = "0.0", path = "../lib" }
clap = { version = "4.3.12", features = ["derive"] }
hex = "0.4.3"

[dev-dependencies]
duct = "0.13.5"
tempfile = "3.2.0"
