[package]
name = "bessie_bin"
version = "0.0.0"
edition = "2021"
description = "a demo/test CLI for Bessie, NOT FOR PRODUCTION USE"

[[bin]]
name = "bessie"
path = "src/main.rs"

[dependencies]
bessie = { path = "../lib" }
clap = { version = "3.0.0", features = ["derive"] }
hex = "0.4.3"

[dev-dependencies]
duct = "0.13.5"
tempfile = "3.2.0"
